version: "3"

services:
  #Database service
  mysql_db:
    container_name: mysql_container
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass123
      MYSQL_DATABASE: skyland
      MYSQL_USER: skyland
      MYSQL_PASSWORD: pass123
    volumes:
      - mysql:/var/lib/mysql

  #Wordpress (image based on Apache)
  wordpress:
    depends_on:
      - mysql_db
    image: wordpress:latest
    restart: always
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: mysql_db:3306
      WORDPRESS_DB_USER: skyland
      WORDPRESS_DB_PASSWORD: pass123
      WORDPRESS_DB_NAME: skyland
    volumes:
      - "./:/var/www/html"
      - "./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini"

  #phpMyAdmin service
  phpmyadmin:
    depends_on:
      - mysql_db
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_container
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql_db
      PMA_USER: root
      PMA_PASSWORD: pass123
    links:
      - mysql_db:mysql
    volumes:
      - /sessions

volumes:
  mysql: {}
